# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SFS.Plan' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod 'SDWebImage', '~> 4.0.0-beta2'
  pod 'SVProgressHUD', '~> 2.0.4'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'MJExtension', '~> 3.0.13'
  # Pods for SFS.Plan

end
